### ISSUE TITLE
哥们怎么联系你啊

### ISSUE THREAD

**Issue by mrchachacha** [Dylanchouxd/Autojs_Douyin#2]
这个失效了 能不能更新一下 有偿

**Comment by mrchachacha** [comment]
可以出费用啊 麻烦作者联系我一下

**Comment by QQOQ** [comment]
> 可以出费用啊 麻烦作者联系我一下

改一下吧，我用最新版抖音重新 实现了下，感觉没问题

**Comment by Dylanchouxd** [comment]
脚本中使用了 APP 的元素 ID 去匹配对应的操作位置，正常来说只要 APP 不更新，脚本就是正常的。

但是如果你要适配最新版的软件，就要相对应更改元素匹配的 ID。

就是项目上的 id("com.ss.android.ugc.aweme:id/***") id("com.smile.gifmaker:id/***") 之类的东西。

本来我想把这些获取控件的 id 整成一个变量的，但是后期没有时间去维护所以也没去处理了。

**Comment by yuan170923** [comment]
> > 可以出费用啊 麻烦作者联系我一下
> 
> 改一下吧，我用最新版抖音重新 实现了下，感觉没问题

怎么做到的

**Comment by Dylanchouxd** [comment]
[已适配新版本抖音](https://github.com/Dylanchouxd/Autojs_Douyin/releases/tag/1.1.0)
